### ISSUE TITLE
Interceptor response leads with 0x1b unicode character which breaks JSON parse

### ISSUE THREAD

**Issue by WesleyYue** [mswjs/interceptors#323] opened 2022-12-17 02:14 UTC
I have the following code:
```
interceptor.on("response", async (response, _request, requestId) => {
    const isJsonContentType = response.headers.get("content-type")?.includes("application/json");
    let body;

    if (isJsonContentType) {
      body = await response.clone().json();
    } else {
      body = await response.clone().text();
    }

    functions.logger.debug("Response from Outgoing HTTP Req", {
      ...response,
      body: body,
      headers: Object.fromEntries(response.headers.entries()),
      requestId: requestId,
    });
  });
  ```
  
 - I'm using this to log all HTTP responses on an express app.
 - I'm using axios to execute HTTP requests
 - Occasionally, I get this error that says it cannot parse the JSON because it has a unexpected character (invisible/escape unicode character 0x1b) at position 0. This happens when I call an external API, from which I expect to receive a valid JSON object containing unicode characters. In reality, I simultaneously, for the same response:
     - receive a invalid JSON object leading with 0x1b in msw interceptor
     - receive a valid JSON object with unicode in my axios return value (which is what I expect)
 - The 'content-type' header of the response is "application/json; charset=utf-8"
 - Printing the contents via `response.text()` shows the following: `\u001b�U�\bI��\u0010@UUU='\u0.......`

I don't think the issue is with the external API since my actual call in axios can parse the data just fine, it is only the intercepted msw log that breaks (for the exact same response). Do you have any clues as to whether something inside msw interceptor is corrupting the response stream?

**Comment by kettanaito** [comment] 2022-12-19 10:42
Hey, @WesleyYue. Thanks for reporting this. 

Could you please create a reproduction repository for this issue? Then I'd be able to help you see what's going on. 

Overall, the response you get looks like a binary response. When it happens, go and request that URL as-is, and see what it returns. I suspect this is the issue with either what is being fetched or with the server that responds with a binary when you expect JSON. 

I will close the issue until the reproduction repository is provided. Thanks for understanding.

**Closed by kettanaito** 2022-12-19 10:42 UTC
