### ISSUE TITLE
socket.io timeout

### ISSUE THREAD

**Issue by wanglong167** [mswjs/interceptors#61] opened 2020-10-14 07:17 UTC
socket.io timeout

**Comment by kettanaito** [comment] 2020-10-14 09:43
Hey, @wanglong167. It looks like your issue description is empty. Could you provide more details, for instance:

- How are you using `node-request-interceptor`?
- Showcase you're tests/NodeJS code.
- What is the current behavior (be explicit, include your guesses over the cause, error messages, and any other info you find relevant)?
- What is the expected behavior?

Without this info we cannot look into this issue. Thanks for the understanding.

**Comment by kettanaito** [comment] 2020-10-14 09:45
Also note that NRI, as well as MSW, **do not support WebSocket yet**. There is a pull request opened to introduce that support in MSW: https://github.com/mswjs/msw/pull/396.

**Comment by wanglong167** [comment] 2020-10-14 09:56
socket.js
```
var express = require('express');
var app = express();
var path = require('path');
var server = require('http').createServer(app);
var io = require('socket.io')(server);
var port = process.env.PORT || 3000;

server.listen(port, () => {
  console.log('Server listening at port %d', port);
});

// Routing
app.use(express.static(path.join(__dirname, 'public')));

// Chatroom
 

io.on('connection', (socket) => {
   console.log('socket connection')

  // when the user disconnects.. perform this
  socket.on('disconnect', () => {
    console.log('socket disconnect')
  });
});
```



app.js
```
const { RequestInterceptor } = require('node-request-interceptor')
const withDefaultInterceptors = require('node-request-interceptor/lib/presets/default').default

const interceptor = new RequestInterceptor(withDefaultInterceptors)

interceptor.use((req) => {
  // Will print to stdout any outgoing requests
  // without affecting their responses
  console.log('%s %s', req.method, req.url.href)
  
})

const socketIoClient = require('socket.io-client');
const socket =  socketIoClient("http://localhost:3000",  {
  timeout: 5000,
  transports: ['websocket']
});
socket.on('connect', () => {
  console.log('connect.....');
  // console.log('connect');
});
socket.on('connect_error', (err) => {
  console.log('connect_error.....', err.message); 
});
socket.on('connect_timeout', () => {
  console.error('connect_timeout.....');
});
socket.on('error', (err) => {
  console.error('error', err);
});
```

**Comment by kettanaito** [comment] 2020-10-15 08:43
There is no WebSocket support in NRI at the moment. You can contribute to the progress in this pull request: https://github.com/mswjs/msw/pull/396. I'm afraid your issue cannot be tackled, because it lies outside of the supported scope of the library.

**Comment by wanglong167** [comment] 2020-10-21 13:28
No need to support websocket, but introducing this module will cause an exception

**Comment by wanglong167** [comment] 2020-10-21 13:29
@kettanaito

**Comment by kettanaito** [comment] 2020-10-22 07:51
What is the intention of introducing NRI into a WebSocket communication? 

Since the WS are not supported, you won't get anything intercepted. Moreover, there is no guarantee how NRI will work in the same environment as a WS connection. Even if you connect to the HTTP server via a WS client it's still a WS connection. We can look at this as a part of WS support, but it's not something we should treat as an issue, if I understand the usage correctly.

**Comment by kf6kjg** [comment] 2021-02-01 16:36
@kettanaito I think that's the point: either NRI needs to not cause issues with WS, or it needs to support it.  Right now, NSI v0.5.8, the simple example posted above using `new RequestInterceptor(withDefaultInterceptors)` results in NSI incorrectly intercepting Socket.io connections and prematurely dropping them.  It shouldn't even be attaching to them.

**Comment by drericrobinson** [comment] 2021-03-11 16:42
Yeah I'm running into this same issue. Ideally NSI should just let the socket connections just pass through, rather than intercepting them.

I'm not trying to test the socket connections, but I'm getting console errors simply b/c they're happening

**Comment by kettanaito** [comment] 2021-03-22 00:45
Can somebody please submit a reproduction repository of this? I've tried following the code above, but it doesn't even compile (using TypeScript). I'd like to solve this, but I need a reliable reproduction that I will then convert into a test. Thanks.

**Comment by kettanaito** [comment] 2021-07-03 10:35
We've recently released a bug fix concerning a custom HTTP socket timeout in `0.12.1`. This may be related to the issue. 

Due to the lack of a reproduction repository, I'm closing this. If you face this issue, please create a repository on GitHub where I, or other maintainers, could investigate.

**Closed by kettanaito** 2021-07-03 10:35 UTC
