### ISSUE TITLE
Error with require

### ISSUE THREAD

**Issue by brucejcw** [mswjs/interceptors#195] opened 2022-01-05 03:18 UTC
**Cannot read properties of undefined (reading 'content-encoding')**

```
const { createInterceptor } = require('@mswjs/interceptors')
const nodeInterceptors = require('@mswjs/interceptors/lib/presets/node').default

const interceptor = createInterceptor({
    modules: nodeInterceptors,
    resolver(request, ref) {
        return {
            status: 200,
            statusText: 'OK',
            headers: {
                'content-type': 'application/json',
                'x-header': 'yes'
            },
            body: JSON.stringify({
                success: true,
            }),
        }
    },
})

interceptor.apply()
```
![image](https://user-images.githubusercontent.com/8085088/148155431-791a879b-571d-415e-99b1-63a71643ee06.png)

**Comment by kettanaito** [comment] 2022-01-07 10:52
Hey, @brucejcw. Thanks for reporting this. 

Unfortunately, I cannot reproduce this issue using the code above. `response.headers` always exist in my case. 

Could you please prepare a reproduction repository for me to look at? I'd like to investigate this issue and put it into a test suite if there's a problem on our side.

**Comment by kettanaito** [comment] 2022-01-24 10:58
I'm closing this due to the lack of the reproduction scenario. If you still experience this, please create one and post it here, I'd be glad to look into it. Thanks.

**Closed by kettanaito** 2022-01-24 10:58 UTC
Labels: needs:reproduction

**Comment by jaydeepkarena** [comment] 2022-01-25 09:00
i am also getting the same error....

**Comment by jaydeepkarena** [comment] 2022-01-25 09:02
i am also getting the same error...
i am using following code for testing

`const express = require('express')
const fetch = require('node-fetch')
const {createInterceptor} = require('@mswjs/interceptors')
const nodeInterceptors = require('@mswjs/interceptors/lib/presets/node').default

const app = express()
const port = 3000

function _instrumentHTTPTraffic() {
  const interceptor = createInterceptor({
    resolver: () => {}, // Required even if not used
    modules: nodeInterceptors,
  })

  interceptor.on('request', _handleHttpRequest)

  interceptor.on('response', _handleHttpResponse)

  interceptor.apply()
}

function _handleHttpRequest(request) {
  console.log('>>> _handleHttpRequest')
  const url = request.url.toString()
  const method = String(request.method)
  const headers = request.headers.raw()
  const body = request.body

  const requestEvent = {
    headers,
    method,
    url,
    body,
  }

  // Intentionally not waiting for a response to avoid adding any latency with this instrumentation
  LogRequest(requestEvent)
}

function _handleHttpResponse(request, response) {
  console.log('>>> _handleHttpResponse')
  const url = request.url.toString()
  const headers = request.headers.raw()
  console.log('>>> ', url, headers)

  const responseEvent = {
    url: request.url.toString(),
    method: request.method,
    body: response.body,
    headers: response.headers.raw(),
    statusCode: response.status,
  }

  // Intentionally not waiting for a response to avoid adding any latency with this instrumentation
  LogResponse(responseEvent)
}

function LogRequest(requestEvent) {
  console.log('>>> REQUEST >>> ', requestEvent)
}

function LogResponse(responseEvent) {
  console.log('>>> RESPONSE >>> ', responseEvent)
}

_instrumentHTTPTraffic()

app.get('/', async (req, res) => {
  try {
    const fakeData = `https://jsonplaceholder.typicode.com/posts/1/comments`
    const response = await fetch(fakeData)
    const json = await response.json()
    // console.log(json)
    res.json(json)
  } catch (error) {
    console.log('>>> ', error)
    res.send(error)
  }
})

app.get('/sample-post', async (req, res) => {
  try {
    // Example POST method implementation:
    async function postData(url = '', data = {}) {
      // Default options are marked with *
      const response = await fetch(url, {
        method: 'POST', // *GET, POST, PUT, DELETE, etc.
        mode: 'cors', // no-cors, *cors, same-origin
        cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
        credentials: 'same-origin', // include, *same-origin, omit
        headers: {
          'Content-Type': 'application/json',
          // 'Content-Type': 'application/x-www-form-urlencoded',
        },
        redirect: 'follow', // manual, *follow, error
        referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
        body: JSON.stringify(data), // body data type must match "Content-Type" header
      })
      return response.json() // parses JSON response into native JavaScript objects
    }

    const response = await postData(`https://jsonplaceholder.typicode.com/posts`, {answer: 42})
    console.log('normal response... ', response)

    res.send('Done....')
  } catch (error) {
    console.log('>>> ', error)
    res.send(error)
  }
})

app.listen(port, () => {
  console.log(`Example app running at http://localhost:${port}`)
})
`

**Comment by kettanaito** [comment] 2022-01-25 15:10
Please, @jaydeepkarena, may I ask you to isolate this code snippet into a reproduction repository? I really can't debug it unless I can run it on my machine. Thanks for understanding.

**Comment by jaydeepkarena** [comment] 2022-01-25 15:44
do you mean i should host it some where, or push the whole project into a repo ?

**Comment by kettanaito** [comment] 2022-01-25 16:51
You can try to reproduce this error in a clean repository. This has a decent chance of helping you discover what's the issue is as well, as it often happens. If you can, you may push your code to GitHub as-is, just be careful when it comes to NDAs and other company regulations, I don't encourage you to break those.

**Comment by jaydeepkarena** [comment] 2022-01-27 06:37
Hi, @kettanaito 

i have pushed the code to a [github repo](https://github.com/jaydeepkarena/sample-interceptor)

can you please run this code and look into the issue.

For my use case i just want to log all the 3rd party api calls request and response

**Comment by kettanaito** [comment] 2022-01-31 00:29
Thanks for the follow-up.

The repo seems to function without issues for me.

- node v14.17.0
- npm 6.14.13
- @mswjs/interceptors@0.13.1

`GET /`:
```
>>> _handleHttpRequest
>>> REQUEST >>>  {
  headers: {
    accept: '*/*',
    'user-agent': 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)',
    'accept-encoding': 'gzip,deflate',
    connection: 'close',
    host: 'jsonplaceholder.typicode.com'
  },
  method: 'GET',
  url: 'https://jsonplaceholder.typicode.com/posts/1/comments',
  body: ''
}
>>> _handleHttpResponse
>>> RESPONSE >>>  {
  url: 'https://jsonplaceholder.typicode.com/posts/1/comments',
  method: 'GET',
  body: '[\n' +
    '  {\n' +
    '    "postId": 1,\n' +
    '    "id": 1,\n' +
    '    "name": "id labore ex et quam laborum",\n' +
    '    "email": "Eliseo@gardner.biz",\n' +
    '    "body": "laudantium enim quasi est quidem magnam voluptate ipsam eos\\ntempora quo necessitatibus\\ndolor quam autem quasi\\nreiciendis et nam sapiente accusantium"\n' +
    '  },\n' +
    '  {\n' +
    '    "postId": 1,\n' +
    '    "id": 2,\n' +
    '    "name": "quo vero reiciendis velit similique earum",\n' +
    '    "email": "Jayne_Kuhic@sydney.com",\n' +
    '    "body": "est natus enim nihil est dolore omnis v',
  headers: {
    date: 'Mon, 31 Jan 2022 00:28:07 GMT',
    'content-type': 'application/json; charset=utf-8',
    'transfer-encoding': 'chunked',
    connection: 'close',
    'x-powered-by': 'Express',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '999',
    'x-ratelimit-reset': '1643136171',
    vary: 'Origin, Accept-Encoding',
    'access-control-allow-credentials': 'true',
    'cache-control': 'max-age=43200',
    pragma: 'no-cache',
    expires: '-1',
    'x-content-type-options': 'nosniff',
    etag: 'W/"5e6-4bSPS5tq8F8ZDeFJULWh6upjp7U"',
    'content-encoding': 'gzip',
    via: '1.1 vegur',
    'cf-cache-status': 'HIT',
    age: '4634',
    'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=0Px2uhPO%2F4ZpMEA0hXHGAINs7GR%2B1mEcKr%2BMNZK7J1saDhimYgwmigQw0NdToBGuKjXfyX9jgavoJOQoW9CU%2BoGniRe%2B7cg9egiXwwEGd7sWvQqYBcLaiOsDE5v5TfomSSWDcdx2F6XYsAmsMBZ%2B"}],"group":"cf-nel","max_age":604800}',
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    server: 'cloudflare',
    'cf-ray': '6d5ed17569415c1a-FRA',
    'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
  },
  statusCode: 200
}
```

`GET /simple-post`:

```
>>> _handleHttpRequest
>>> REQUEST >>>  {
  headers: {
    'content-type': 'application/json',
    accept: '*/*',
    'content-length': '39',
    'user-agent': 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)',
    'accept-encoding': 'gzip,deflate',
    connection: 'close',
    host: 'jsonplaceholder.typicode.com'
  },
  method: 'POST',
  url: 'https://jsonplaceholder.typicode.com/posts',
  body: '{"title":"foo","body":"bar","userId":1}'
}
>>> _handleHttpResponse
>>> RESPONSE >>>  {
  url: 'https://jsonplaceholder.typicode.com/posts',
  method: 'POST',
  body: '{\n  "title": "foo",\n  "body": "bar",\n  "userId": 1,\n  "id": 101\n}',
  headers: {
    date: 'Mon, 31 Jan 2022 00:27:38 GMT',
    'content-type': 'application/json; charset=utf-8',
    'content-length': '65',
    connection: 'close',
    'x-powered-by': 'Express',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '998',
    'x-ratelimit-reset': '1643588864',
    vary: 'Origin, X-HTTP-Method-Override, Accept-Encoding',
    'access-control-allow-credentials': 'true',
    'cache-control': 'no-cache',
    pragma: 'no-cache',
    expires: '-1',
    'access-control-expose-headers': 'Location',
    location: 'http://jsonplaceholder.typicode.com/posts/101',
    'x-content-type-options': 'nosniff',
    etag: 'W/"41-GDNaWfnVU6RZhpLbye0veBaqcHA"',
    via: '1.1 vegur',
    'cf-cache-status': 'DYNAMIC',
    'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=%2BLp%2BMTkAcsG8hyJWY6NO0C0HtEoHBmDHSKwmBK2IfQhmJLRMxXM9%2BqU8Jf4Bgl7VCCo1LL4j2wkj%2FGotPEoW2vQYsI42UlBowWGemTul%2BAFPrxzzObi2Eyaa9rKLaBq17uUIPdcESdENomW1ACad"}],"group":"cf-nel","max_age":604800}',
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    server: 'cloudflare',
    'cf-ray': '6d5ed0bd1b3a5c6e-FRA',
    'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
  },
  statusCode: 201
}
```

Is this what you expect to see in the terminal when hitting the endpoints? 

You may want to ensure your node/npm/dependencies are up-to-date and try again.

**Comment by jaydeepkarena** [comment] 2022-01-31 06:42
Thanks @kettanaito it is working for me as well

don't know what was the issue
