### ISSUE TITLE
Not able to use client request interceptor from client request

### ISSUE THREAD

**Issue by RaviPublicis** [mswjs/interceptors#372] opened 2023-04-25 11:06 UTC
While importing ClientRequestInterceptor from '@mswjs/interceptors/ClientRequest', getting module not found and not mentioned export of 'node_modules/@mswjs/interceptors/package.json'

**Comment by kettanaito** [comment] 2023-04-25 11:35
Hi, @RaviPublicis. Thanks for reporting this. Do you have a reproduction repository I can look at? I'm afraid I cannot suggest much without it.

**Comment by allenhwkim** [comment] 2023-04-26 21:31
I had the same issue and I m down versioning to v0.20.0

```
import { ClientRequestInterceptor } from '@mswjs/interceptors/lib/interceptors/ClientRequest';
const interceptor = new ClientRequestInterceptor();
```

I m having issue with v0.22 becuase of;

1. node version(I use 16, but it requires >=18)
2. It also does not export ClientRequestInterceptor as I see the code.

**Comment by kettanaito** [comment] 2023-04-27 13:44
@allenhwkim that is correct. There have been some breaking changes since 0.20 in regard to the package's exports. You should not use the `/lib/X` import paths anymore as the library has the root-level paths instead.

```js
import { ClientRequestInterceptor } from '@mswjs/interceptors/ClientRequest'
```

I can confirm this works as expected since our integration tests are also using these imports. 

If you're getting import errors, please check your tooling and ensure that it supports import conditions (although this shouldn't be the case, to begin with, because we also ship root-level directories to support legacy tooling). 

> node version(I use 16, but it requires >=18)

Sorry, you have to migrate to Node 18 to use this library. Node 16 is extremely old and will reach EOL this autumn. This is a good time to migrate. 

I will close this issue for the lack of a reproduction repository. If you have one, post it here and I will reopen and look into it. Thanks.

**Closed by kettanaito** 2023-04-27 13:44 UTC
