### ISSUE TITLE
XMLHttpRequest: Support "upload" events

### ISSUE THREAD

**Issue by kettanaito** [mswjs/interceptors#187] opened 2021-11-14 18:10 UTC
The `upload` property on the XMLHttpRequest returns a `XMLHttpRequestUpload` instance, which is similar to an event emitter. The consumer may use the `upload` instance to attach listeners on the _request body_ upload progress.

```js
const req = new XMLHttpRequest()
req.open('POST', '/upload')
req.upload.addEventListener('progress', (event) => {
  if (event.lengthComputable) {
    console.log('%d / %d', event.loaded, event.total)
  } 
})
```

We should enable the `upload` events for both mocked and bypassed requests. 

## Event order

The upload events are called in the following order, given request body:

1. `loadstart`, request body is known, the `lengthComputable` value on the `ProgressEventInit` is set to a boolean representing if there's any upload work to be done (request has body).
2. `progress`, request body is known and read, the progress event contains `loaded` and `total` of transferred request body bytes.
3. `load`.
4. `loadend`, the upload is over.

**Comment by eudinnou** [comment] 2022-05-04 09:58
hi @kettanaito, is there any chance that this will get fixed in the near future?

**Comment by kettanaito** [comment] 2022-05-04 10:49
Hey, @eudinnou. This task is not on my list at the moment so I don't know when I'll get to it. That being said, you and anybody else are welcome to open a pull request with the implementation for XMLHttpRequest events. I believe I've described what has to be done in the issue's description. If you feel like making this happen, let me know and I will help you during the code reviews.

**Closed** 2022-11-07 18:23 UTC

**Comment by kettanaito** [comment] 2022-11-07 18:32
## Released: v0.18.0 🎉

This has been released in v0.18.0!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.18.0)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.18.0)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by KKrisu** [comment] 2023-02-06 13:43
cool, but unfortunately it doesn't work with MSW itself :/

    > TypeError: Class extends value undefined is not a constructor or null

    > 1 | import { rest } from 'msw';

**Comment by kettanaito** [comment] 2023-02-06 14:41
@KKrisu, MSW uses [Interceptors v17](https://github.com/mswjs/msw/blob/12a581f480e3a2f9bdcda7874f98114c148c9d85/package.json#L91) right now so this change is respectively not present there yet. It will be added with the Fetch API support later this year.

**Comment by KKrisu** [comment] 2023-02-06 15:44
ok, we need to wait then, thank you @kettanaito

**Comment by kokiy** [comment] 2023-02-13 11:17
> @KKrisu, MSW uses [Interceptors v17](https://github.com/mswjs/msw/blob/12a581f480e3a2f9bdcda7874f98114c148c9d85/package.json#L91) right now so this change is respectively not present there yet. It will be added with the Fetch API support later this year.

I also encountered this problem

**Comment by kokiy** [comment] 2023-02-13 11:18
> cool, but unfortunately it doesn't work with MSW itself :/
> 
> ```
> > TypeError: Class extends value undefined is not a constructor or null
> 
> > 1 | import { rest } from 'msw';
> ```
I also encountered this problem, I hope the official fixes it as soon as possible

**Comment by kettanaito** [comment] 2023-02-13 15:26
@kokiy please do not update `@mswjs/interceptors` manually. MSW on its `latest` tag relies on `@mswjs/interceptors@0.17` and _it should stay that way_. 

https://github.com/mswjs/msw/blob/2633fa93af4bcbc33f12f69a6b83193684c3dfd3/package.json#L91

What you're doing is installing the next breaking version (0.18.0). Of course, things will break, they are promised to break.

**Comment by kokiy** [comment] 2023-02-14 02:56
@kettanaito 
<img width="1805" alt="image" src="https://user-images.githubusercontent.com/15773714/218627009-8c9fa60f-3986-4e76-831c-1a2181cc91ae.png">
I followed the tutorial to configure step by step, but an error was reported, and I don't know where the problem is

repo link:  https://github.com/kokiy/react-webpack-demo

**Comment by itzfeltrin** [comment] 2023-10-25 14:14
will MSW 1 be updated to use mswjs/interceptors@0.18 or obove?

**Comment by Lemon-Cai** [comment] 2023-11-24 05:34
I'm having this problem too. use msw@2.0.8. How to do resovle this problem. use `@mswjs/interceptors` ? how to config

**Comment by jaredhill4** [comment] 2024-01-10 16:34
@kettanaito,

Is this update now available in the latest version of `msw`? I'm needing it, also.

Thank you!
