### ISSUE TITLE
Arraybuffer response in XMLHttpRequest assumes always to be a string?

### ISSUE THREAD

**Issue by chananababa** [mswjs/interceptors#158] opened 2021-10-17 08:00 UTC
I am trying to mock a XMLHttpRequest which get image file data as an arraybuffer. However, I observed some unexpected behaviors with the mocked response.

1. The response attribute always set to be a Uint8Array rather than ArrayBuffer.
2. Even if the body of MockedResponse is already set an arraybuffer, 'bufferfrom' function assumes it as a string and encodes it. It results an encoded string like '<Object ArrayBuffer>'.
3. ResponseText attribute is directly set to be the original response body. So if I send an arraybuffer, response attribute is a string and responseText attribute is an arraybuffer.

**Comment by bartbutenaers** [comment] 2021-10-19 15:39
Hi @ephong93,
I have been struggling with the same issue last night.  I first thought that our application was instructing NodeJs incorrectly to convert buffers to strings.  But then it seemed that the `bodyBufferToString` of this library is converting the response body from buffer to string.
It would be nice if buffers could be left unchanged.  Perhaps this can be configured as an option?
Thanks!!
Bart

**Comment by bartbutenaers** [comment] 2021-11-04 20:38
Hello @kettanaito,
This issue is the only one that prevents me from migrating my application to use this library. 
It would be nice to get an idea about our request seems acceptable, or is it perhaps not possible due to some technical reasons or other concerns?
Looking forward to hear your ideas about this.
Thanks again !!
Bart

**Comment by kettanaito** [comment] 2021-11-09 11:38
Hey, @ephong93. Thank you for reporting this. It does look like an issue on our side.

@bartbutenaers, this request is acceptable and should be fixed. Ideally, I'd like to rewrite the current XMLHttpRequest interceptor to extend the XMLHttpRequest class instead of replacing it (similar to what we did with `ClientRequest` in #116). This rewrite would have a number of benefits, such as allowing XHR instance to call all the internal methods properly (including response body handling), but will impose some challenges as well, such as the requirement on our side to prevent the actual connection until we are sure the `resolver` function returns no mocked response. 

> That being said, unlike `ClientRequest`, XMLHttpRequest does have a designated `.open()` method, which, I'd expect, is responsible for opening a socket connection. We could override that method and call `super.open()` to establish the actual connection for bypassed requests only when the `resolver` function returns nothing.

Do you have any proposed solution in mind that could address this with the current state of the library? I wouldn't wish for you to wait for a full-scale interceptor rewrite just to get this fixed. 

**Before we discuss this, could you ensure that the issue is indeed in the XMLHttpRequest instance?** Thing is, XHR is polyfilled in Node.js one way or another. Sometimes you may use a designated XMLHttpRequest polyfill (such as the one from JSDOM), and sometimes XHR is implemented using `ClientRequest`. To make sure we're discussing the right thing, could you please check that?

You can verify that by running your problematic test/scenario with the `DEBUG=*` flag. It will print additional interception info along the way. Look at those logs and see if any of them start from `http ...`. If they do, then we're talking about an issue in the `ClientRequest` interceptor. If they don't, and you see `XHR` instead, then we're scoped to the respective interceptor instead. 

---

> The response attribute always set to be a Uint8Array rather than ArrayBuffer.

That's likely an issue while converting a mocked response string body to "arraybuffer" response type:

https://github.com/mswjs/interceptors/blob/9d4cfa413dfa6d2d7e558962a6e76a5ebdea0135/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L505-L509

I'd like to ask you for help in suggesting how to rewrite this block so that we preserve the array buffer bodies intact. 

> Even if the body of MockedResponse is already set an arraybuffer, 'bufferfrom' function assumes it as a string and encodes it. It results an encoded string like ''.

That's the thing, this library always expects a string as the mocked response body. So we always expect a string, and convert it to necessary response types accordingly (such as calling `bufferFrom`).

> ResponseText attribute is directly set to be the original response body. So if I send an arraybuffer, response attribute is a string and responseText attribute is an arraybuffer.

That is a bug and it manifests here:

https://github.com/mswjs/interceptors/blob/9d4cfa413dfa6d2d7e558962a6e76a5ebdea0135/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L296

This library is written to always expect a `string` as the value of the mocked response. That's why we've assigned `this.responseText` to `mockedResponse.body` safely: 

https://github.com/mswjs/interceptors/blob/9d4cfa413dfa6d2d7e558962a6e76a5ebdea0135/src/createInterceptor.ts#L33-L38

The fact that you see an `ArrayBuffer` in `this.responseText` suggest you're not using `@mswjs/interceptors` directly. Is that the case? Does this issue manifest when using [MSW](https://github.com/mswjs/msw)?

**Comment by kettanaito** [comment] 2021-11-10 01:07
It'd be great to contribute with a failing integration test that allows us to reproduce this issue.

**Comment by ephong93** [comment] 2021-11-14 23:56
Hi, @kettanaito !
Thank you for the detailed response. I tried to reproduce the case, but I failed to find a way to run MSW in fallback mode in test code. So I opened a http server and you can access it to see the output of XMLHttpRequest: http://18.222.230.65:3000/
And the source code is here: https://github.com/ephong93/msw-interceptor-test

> Before we discuss this, could you ensure that the issue is indeed in the XMLHttpRequest instance?

In the source code, I created an XMLHttpRequest object for the request and I checked that the type of the object was 'XMLHttpRequestOverride' so I think I am pretty sure that I am using mswjs/interceptors and the overrided XMLHttpRequest class. 


> It'd be great to contribute with a failing integration test that allows us to reproduce this issue.

This is a failing test code for the case which can be inserted in 'test/rest-api/response/body/body-binary.node.test.ts' in 'mswjs/msw'.


```
test('returns arraybuffer in the mocked XMLHttpRequest response', async () => {
  const getImageBufferFromXHR = (url: string): Promise<ArrayBuffer> => new Promise((resolve) => {
    const xhr = new XMLHttpRequest()
    xhr.open('GET', url)
    xhr.responseType = 'arraybuffer'
    xhr.onreadystatechange = () => {
      if (xhr.readyState === XMLHttpRequest.DONE) {
        resolve(xhr.response)
      }
    }
    xhr.send()
  })
  const actualImageBuffer = await getImageBufferFromXHR('http://test.mswjs.io/image')
  const expectedImageBuffer = getImageBuffer()
  expect(Buffer.compare(actualImageBuffer, expectedImageBuffer)).toBe(0)
})
```

**Comment by bartbutenaers** [comment] 2021-11-15 22:49
@kettanaito,
Thanks for the extensive feedback!  
Sorry for the delay, but I am a bit too busy last days.  
I will get back to you somewhere this week ...

**Comment by bartbutenaers** [comment] 2021-11-24 21:18
@kettanaito,
Apologies for the delay!

> Do you have any proposed solution in mind that could address this with the current state of the library? I wouldn't wish for you to wait for a full-scale interceptor rewrite just to get this fixed.

Well you shouldn't start implementing temporary workarounds for my use case!  Wouldn't like you to end up with dirty code or backwards compatibility issues.  There is no need to hurry!  I can wait for your rewrite.  It is open-source after all...

> You can verify that by running your problematic test/scenario with the DEBUG=* flag.

My code is a plugin for a large open-source application.  When I start that application on my Windows 10 portable (with that debug flag), I get a massive amount of logs.  I have tried to isolate the logs related to my http request (to get the pexels-photo-373912.jpeg image from the web).  I have included them here, because I am not quite sure which particular "http" keyword you are searching for:

[log.txt](https://github.com/mswjs/interceptors/files/7598715/log.txt)

But when I isolate my code to a separate got_test.js file:
```
const got = require('got');

(async () => {
    const url ="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png";
    const actualImageBuffer = await got(url, {responseType: 'buffer'});
    //console.log(actualImageBuffer.body);
})();
```
And I run it as `set DEBUG=* & node got_test.js`, then I get no logs at all.  Don't really understand why...
If there is anything else I can test, don't hesitate to let me know!!

Thanks!
Bart

**Comment by kettanaito** [comment] 2021-12-08 12:36
Thank you for the follow-up, @bartbutenaers. 

The overall request/response body handling in the XMLHttpRequest interceptor can be improved. I've attempted to facilitate this in the interceptor's rewrite (#184) but, unfortunately, I haven't found the right way to compile the library so it'd preserve the `class` syntax and allow for the native browser classes extension. For now, I'd treat that refactoring as experimental.

To recap: the proposed change is to preserve the original response buffer body. At the moment, the "arraybuffer" `responseType` is handled like this:

https://github.com/mswjs/interceptors/blob/1d35db531d14a7f95126a382b005451af927924c/src/interceptors/XMLHttpRequest/XMLHttpRequestOverride.ts#L505-L509

https://github.com/mswjs/interceptors/blob/1d35db531d14a7f95126a382b005451af927924c/src/interceptors/XMLHttpRequest/utils/bufferFrom.ts#L5-L16

I suppose `bufferFrom` does not recreate a proper buffer from the given string? 

I'd much appreciate some help in rewriting the `bufferFrom` function, it seems to be the culprit.

**Comment by kettanaito** [comment] 2022-10-13 13:58
There's a substantial improvement done to how XMLHttpRequest request and response bodies are handled in #292. I think this issue should be resolved once that change lands, at least partially. 

We still keep response body as `Uint8Array` internally but when you would access `this.response` with `this.responseType = 'arraybuffer` we would convert that into `ArrayBuffer` and return it to you.

**Comment by MiluchOK** [comment] 2022-10-19 18:58
Hello! I am a bit confused here if my use case is related. 
I am trying to send a protobuf encoded message as an arraybuffer and I keep getting more bytes on the receiving side. 
I ran my arraybuffer through the `bufferFrom ` method mentioned above and it is exactly what I am getting as response (the original message size + extra bytes).  

How would I be able to mock protobuf array buffer response properly, if I suppose to feed a string that will be encoded in the msw library?

**Comment by kettanaito** [comment] 2022-10-19 20:26
@MiluchOK, I'd recommend waiting for #292 to land.

But if you're blocked by this, I think there's a bug in `bufferFrom()` this library uses. We should use `TextEncoder`, ideally. It's global in the browser and it comes from the `util` built-in package in Node.js. 

https://github.com/mswjs/interceptors/blob/15eafa6215a328219999403e3ff110e71699b016/src/interceptors/XMLHttpRequest/utils/bufferFrom.ts#L5

If you feel like it, you can tackle this in a pull request.

**Comment by MiluchOK** [comment] 2022-10-21 14:08
@kettanaito is it know roughly when https://github.com/mswjs/interceptors/pull/292 is going to land? 
I don't fully understand the flow with the encoding tbh, but will invest in it if the #282 is very far from landing or it doesn't fix my issue. 

Appreciate your help btw!

**Comment by kettanaito** [comment] 2022-10-21 15:08
Those changes depend on a fix to `@remix-run/web-fetch` (https://github.com/remix-run/web-std-io/pull/21) and until it's merged and published they won't run properly. I hope Remix teams helps me make that happen in the upcoming weeks.

**Closed** 2022-11-07 18:23 UTC
Labels: help wanted, scope:xhr, needs:discussion

**Comment by kettanaito** [comment] 2022-11-07 18:32
## Released: v0.18.0 🎉

This has been released in v0.18.0!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.18.0)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.18.0)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by bartbutenaers** [comment] 2022-11-17 22:27
@kettanaito,
Sorry for not responding earlier!  Very busy at the moment...

I have refactored my code to use your new version, and it works very smooth with binary data.
You can see a demo [here](https://discourse.nodered.org/t/announce-node-red-contrib-http-logger-version-3-0-0-beta/70798), where I intercept snapshot images from a public webcam.

Thanks for the solution, and keep up the good work!!!
Bart

**Comment by kettanaito** [comment] 2022-11-17 23:30
I am extremely happy to her that! Thanks.
